#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState

class HandActuatorNode(Node):
    def __init__(self):
        super().__init__('hand_actuator_node')
        self.sub = self.create_subscription(JointState, '/planning/target_joints', self.joint_callback, 10)
        self.get_logger().info("Hand Actuator Node Initialized.")
        self.get_logger().info("Waiting for JointState messages on /planning/target_joints...")

    def joint_callback(self, msg):
        self.get_logger().info("=======================================")
        self.get_logger().info("Received target joints from planner!")
        self.get_logger().info(f"Total Joints: {len(msg.name)}")
        for i in range(len(msg.name)):
            self.get_logger().info(f"{msg.name[i]}: {msg.position[i]:.2f}")
        self.get_logger().info("Actuation simulated successfully.")
        self.get_logger().info("=======================================")

def main(args=None):
    rclpy.init(args=args)
    node = HandActuatorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
